export const problemStatements = {
  Healthcare: [
    {
      title: "Telemedicine for Rural Areas",
      description:
        "Create a telemedicine platform to connect rural patients with healthcare providers, providing diagnostics and basic healthcare services to areas with limited access. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae mollitia animi blanditiis! Doloremque provident quis obcaecati eius voluptatem adipisci? Voluptatibus, quae delectus eligendi quidem fugiat harum, similique, modi expedita in laudantium possimus! Necessitatibus sapiente adipisci nobis? Fugiat corporis, facere a quasi fuga ea fugit, ullam dicta dolorem debitis omnis doloribus in nihil rerum sint inventore beatae corrupti aspernatur porro rem odit tempora officia incidunt. Quidem optio natus cum ipsam totam magnam cumque tenetur id! Dolorum reiciendis nesciunt dicta ipsum odit, eum fugiat, consectetur fugit ut pariatur repellendus est minus. Molestias quasi necessitatibus veritatis excepturi odit. Ipsa id quidem ad. Hic fugiat veritatis debitis impedit eius temporibus possimus, ipsam laboriosam, quam, distinctio facilis quaerat quas repellendus veniam atque aperiam asperiores sequi. Fuga voluptate commodi dolor inventore voluptatum ipsa earum, expedita tenetur omnis aspernatur accusantium veritatis porro, doloribus atque qui numquam illum? Et expedita nisi necessitatibus doloribus beatae, excepturi placeat quis debitis. Sunt aliquid amet omnis dolorum molestias aspernatur! Non maxime reiciendis deserunt unde repudiandae porro dolorem perspiciatis provident recusandae ducimus sapiente tempore, totam voluptas! Sunt repellat, maxime quisquam consequuntur quam natus aliquam saepe ratione! Atque doloribus eum magni quia nulla aliquid, voluptatibus, voluptatem eos iste repudiandae dicta ipsum at asperiores doloremque tenetur voluptate explicabo odio. Eaque numquam tenetur natus repellat alias doloribus fuga asperiores unde tempora nisi temporibus sunt quisquam omnis inventore exercitationem, maxime placeat, iure perspiciatis cumque? Expedita quis alias dicta voluptates molestias error corrupti, fugiat itaque inventore hic fugit, qui iure soluta quibusdam distinctio nisi est nesciunt nobis, rem dolore quae autem iusto. Nam ut vitae debitis molestias accusamus ipsam! Nobis ad ex, quos, corrupti consequatur aut recusandae atque quas alias ratione at odit porro explicabo nihil, molestias fuga incidunt culpa vitae aspernatur numquam illum. Tempora sapiente ratione quaerat et esse, ipsa, quam odit eos maxime at repellendus ab. ",
    },
    {
      title: "AI-Powered Symptom Checker",
      description:
        "Develop an AI-driven app to help users self-check symptoms, offering preliminary advice and recommendations for further care, while being user-friendly and accessible. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae mollitia animi blanditiis! Doloremque provident quis obcaecati eius voluptatem adipisci? Voluptatibus, quae delectus eligendi quidem fugiat harum, similique, modi expedita in laudantium possimus! Necessitatibus sapiente adipisci nobis? Fugiat corporis, facere a quasi fuga ea fugit, ullam dicta dolorem debitis omnis doloribus in nihil rerum sint inventore beatae corrupti aspernatur porro rem odit tempora officia incidunt. Quidem optio natus cum ipsam totam magnam cumque tenetur id! Dolorum reiciendis nesciunt dicta ipsum odit, eum fugiat, consectetur fugit ut pariatur repellendus est minus. Molestias quasi necessitatibus veritatis excepturi odit. Ipsa id quidem ad. Hic fugiat veritatis debitis impedit eius temporibus possimus, ipsam laboriosam, quam, distinctio facilis quaerat quas repellendus veniam atque aperiam asperiores sequi. Fuga voluptate commodi dolor inventore voluptatum ipsa earum, expedita tenetur omnis aspernatur accusantium veritatis porro, doloribus atque qui numquam illum? Et expedita nisi necessitatibus doloribus beatae, excepturi placeat quis debitis. Sunt aliquid amet omnis dolorum molestias aspernatur! Non maxime reiciendis deserunt unde repudiandae porro dolorem perspiciatis provident recusandae ducimus sapiente tempore, totam voluptas! Sunt repellat, maxime quisquam consequuntur quam natus aliquam saepe ratione! Atque doloribus eum magni quia nulla aliquid, voluptatibus, voluptatem eos iste repudiandae dicta ipsum at asperiores doloremque tenetur voluptate explicabo odio. Eaque numquam tenetur natus repellat alias doloribus fuga asperiores unde tempora nisi temporibus sunt quisquam omnis inventore exercitationem, maxime placeat, iure perspiciatis cumque? Expedita quis alias dicta voluptates molestias error corrupti, fugiat itaque inventore hic fugit, qui iure soluta quibusdam distinctio nisi est nesciunt nobis, rem dolore quae autem iusto. Nam ut vitae debitis molestias accusamus ipsam! Nobis ad ex, quos, corrupti consequatur aut recusandae atque quas alias ratione at odit porro explicabo nihil, molestias fuga incidunt culpa vitae aspernatur numquam illum. Tempora sapiente ratione quaerat et esse, ipsa, quam odit eos maxime at repellendus ab.",
    },
    {
      title: "Mental Health Monitoring",
      description:
        "Build a mobile application for tracking mental health, including mood tracking, reminders for self-care, and access to virtual support groups and counseling services. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae mollitia animi blanditiis! Doloremque provident quis obcaecati eius voluptatem adipisci? Voluptatibus, quae delectus eligendi quidem fugiat harum, similique, modi expedita in laudantium possimus! Necessitatibus sapiente adipisci nobis? Fugiat corporis, facere a quasi fuga ea fugit, ullam dicta dolorem debitis omnis doloribus in nihil rerum sint inventore beatae corrupti aspernatur porro rem odit tempora officia incidunt. Quidem optio natus cum ipsam totam magnam cumque tenetur id! Dolorum reiciendis nesciunt dicta ipsum odit, eum fugiat, consectetur fugit ut pariatur repellendus est minus. Molestias quasi necessitatibus veritatis excepturi odit. Ipsa id quidem ad. Hic fugiat veritatis debitis impedit eius temporibus possimus, ipsam laboriosam, quam, distinctio facilis quaerat quas repellendus veniam atque aperiam asperiores sequi. Fuga voluptate commodi dolor inventore voluptatum ipsa earum, expedita tenetur omnis aspernatur accusantium veritatis porro, doloribus atque qui numquam illum? Et expedita nisi necessitatibus doloribus beatae, excepturi placeat quis debitis. Sunt aliquid amet omnis dolorum molestias aspernatur! Non maxime reiciendis deserunt unde repudiandae porro dolorem perspiciatis provident recusandae ducimus sapiente tempore, totam voluptas! Sunt repellat, maxime quisquam consequuntur quam natus aliquam saepe ratione! Atque doloribus eum magni quia nulla aliquid, voluptatibus, voluptatem eos iste repudiandae dicta ipsum at asperiores doloremque tenetur voluptate explicabo odio. Eaque numquam tenetur natus repellat alias doloribus fuga asperiores unde tempora nisi temporibus sunt quisquam omnis inventore exercitationem, maxime placeat, iure perspiciatis cumque? Expedita quis alias dicta voluptates molestias error corrupti, fugiat itaque inventore hic fugit, qui iure soluta quibusdam distinctio nisi est nesciunt nobis, rem dolore quae autem iusto. Nam ut vitae debitis molestias accusamus ipsam! Nobis ad ex, quos, corrupti consequatur aut recusandae atque quas alias ratione at odit porro explicabo nihil, molestias fuga incidunt culpa vitae aspernatur numquam illum. Tempora sapiente ratione quaerat et esse, ipsa, quam odit eos maxime at repellendus ab.",
    },
  ],

  Finance: [
    {
      title: "Budgeting and Expense Tracker",
      description:
        "Design a personal finance tool that allows users to budget, categorize expenses, and set savings goals, focusing on simplicity and user engagement. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae mollitia animi blanditiis! Doloremque provident quis obcaecati eius voluptatem adipisci? Voluptatibus, quae delectus eligendi quidem fugiat harum, similique, modi expedita in laudantium possimus! Necessitatibus sapiente adipisci nobis? Fugiat corporis, facere a quasi fuga ea fugit, ullam dicta dolorem debitis omnis doloribus in nihil rerum sint inventore beatae corrupti aspernatur porro rem odit tempora officia incidunt. Quidem optio natus cum ipsam totam magnam cumque tenetur id! Dolorum reiciendis nesciunt dicta ipsum odit, eum fugiat, consectetur fugit ut pariatur repellendus est minus. Molestias quasi necessitatibus veritatis excepturi odit. Ipsa id quidem ad. Hic fugiat veritatis debitis impedit eius temporibus possimus, ipsam laboriosam, quam, distinctio facilis quaerat quas repellendus veniam atque aperiam asperiores sequi. Fuga voluptate commodi dolor inventore voluptatum ipsa earum, expedita tenetur omnis aspernatur accusantium veritatis porro, doloribus atque qui numquam illum? Et expedita nisi necessitatibus doloribus beatae, excepturi placeat quis debitis. Sunt aliquid amet omnis dolorum molestias aspernatur! Non maxime reiciendis deserunt unde repudiandae porro dolorem perspiciatis provident recusandae ducimus sapiente tempore, totam voluptas! Sunt repellat, maxime quisquam consequuntur quam natus aliquam saepe ratione! Atque doloribus eum magni quia nulla aliquid, voluptatibus, voluptatem eos iste repudiandae dicta ipsum at asperiores doloremque tenetur voluptate explicabo odio. Eaque numquam tenetur natus repellat alias doloribus fuga asperiores unde tempora nisi temporibus sunt quisquam omnis inventore exercitationem, maxime placeat, iure perspiciatis cumque? Expedita quis alias dicta voluptates molestias error corrupti, fugiat itaque inventore hic fugit, qui iure soluta quibusdam distinctio nisi est nesciunt nobis, rem dolore quae autem iusto. Nam ut vitae debitis molestias accusamus ipsam! Nobis ad ex, quos, corrupti consequatur aut recusandae atque quas alias ratione at odit porro explicabo nihil, molestias fuga incidunt culpa vitae aspernatur numquam illum. Tempora sapiente ratione quaerat et esse, ipsa, quam odit eos maxime at repellendus ab."
    },
    {
      title: "Credit Score Improvement Assistant",
      description:
        "Develop an app that helps users understand and improve their credit score by tracking their credit health and offering personalized tips to boost their creditworthiness. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae mollitia animi blanditiis! Doloremque provident quis obcaecati eius voluptatem adipisci? Voluptatibus, quae delectus eligendi quidem fugiat harum, similique, modi expedita in laudantium possimus! Necessitatibus sapiente adipisci nobis? Fugiat corporis, facere a quasi fuga ea fugit, ullam dicta dolorem debitis omnis doloribus in nihil rerum sint inventore beatae corrupti aspernatur porro rem odit tempora officia incidunt. Quidem optio natus cum ipsam totam magnam cumque tenetur id! Dolorum reiciendis nesciunt dicta ipsum odit, eum fugiat, consectetur fugit ut pariatur repellendus est minus. Molestias quasi necessitatibus veritatis excepturi odit. Ipsa id quidem ad. Hic fugiat veritatis debitis impedit eius temporibus possimus, ipsam laboriosam, quam, distinctio facilis quaerat quas repellendus veniam atque aperiam asperiores sequi. Fuga voluptate commodi dolor inventore voluptatum ipsa earum, expedita tenetur omnis aspernatur accusantium veritatis porro, doloribus atque qui numquam illum? Et expedita nisi necessitatibus doloribus beatae, excepturi placeat quis debitis. Sunt aliquid amet omnis dolorum molestias aspernatur! Non maxime reiciendis deserunt unde repudiandae porro dolorem perspiciatis provident recusandae ducimus sapiente tempore, totam voluptas! Sunt repellat, maxime quisquam consequuntur quam natus aliquam saepe ratione! Atque doloribus eum magni quia nulla aliquid, voluptatibus, voluptatem eos iste repudiandae dicta ipsum at asperiores doloremque tenetur voluptate explicabo odio. Eaque numquam tenetur natus repellat alias doloribus fuga asperiores unde tempora nisi temporibus sunt quisquam omnis inventore exercitationem, maxime placeat, iure perspiciatis cumque? Expedita quis alias dicta voluptates molestias error corrupti, fugiat itaque inventore hic fugit, qui iure soluta quibusdam distinctio nisi est nesciunt nobis, rem dolore quae autem iusto. Nam ut vitae debitis molestias accusamus ipsam! Nobis ad ex, quos, corrupti consequatur aut recusandae atque quas alias ratione at odit porro explicabo nihil, molestias fuga incidunt culpa vitae aspernatur numquam illum. Tempora sapiente ratione quaerat et esse, ipsa, quam odit eos maxime at repellendus ab.",
    },
    {
      title: "Micro-Investment Platform",
      description:
        "Create a micro-investment platform allowing users to invest small amounts in diversified portfolios, making investing accessible to young adults and beginners. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae saepe sunt rerum cum velit sit facilis eligendi soluta, esse, unde alias molestiae, doloremque tenetur repellat accusantium dolores aliquam ullam exercitationem. Delectus consequatur quisquam eum modi similique numquam, iusto est explicabo! Voluptatum tempora at aperiam rem magni reprehenderit quasi accusantium quod. Natus totam omnis magni iusto explicabo? Laboriosam vitae mollitia perspiciatis natus excepturi et, corporis debitis in numquam! Illo tempora praesentium quo necessitatibus eius natus accusamus saepe cumque doloribus, suscipit eveniet nemo atque, vitae dolor quae, numquam exercitationem dolorem quidem? Autem fugit nemo iusto molestias pariatur at, culpa ratione, facilis quia rem voluptas adipisci sed provident! Commodi voluptatibus fuga necessitatibus, nulla similique aperiam, atque cupiditate officiis culpa eligendi placeat vero. Quo doloribus necessitatibus maiores amet, est architecto sunt, soluta repellendus commodi corporis aperiam voluptatem eius nulla. Voluptatum, quo culpa? Perspiciatis laudantium quaerat perferendis corrupti adipisci iusto debitis, mollitia saepe nam laboriosam id molestias, quisquam voluptatibus ratione voluptates accusamus dicta, natus cupiditate ex. Nostrum maiores numquam doloribus at vero eos dolores commodi delectus ex alias perspiciatis natus, eius vitae perferendis autem, quis ipsam illum quaerat, est beatae. Veniam modi accusamus consequatur laborum itaque, culpa magnam, aspernatur quisquam mollitia voluptatem inventore, dolorum id perspiciatis optio dolores voluptatum voluptates quae sapiente. Assumenda odit, aspernatur cumque unde cum minus esse sit quidem voluptatem obcaecati necessitatibus, veniam veritatis? Veritatis reiciendis ipsum nisi rem laboriosam quod sapiente aliquam mollitia voluptatibus voluptates id voluptatum veniam quisquam delectus in, dignissimos quos fugit culpa eaque dolore laborum pariatur nesciunt. Cupiditate maiores pariatur, quidem consectetur expedita et error voluptas perspiciatis repudiandae ad illum molestiae magni eaque consequuntur, excepturi distinctio. Similique tenetur recusandae rem quas placeat hic reiciendis dolorem beatae assumenda, vel, quibusdam aspernatur, officiis et necessitatibus quasi ex alias dignissimos ipsa quo. Nesciunt recusandae est quae sint doloremque perferendis adipisci mollitia?",
    },
  ],
};

